application: gamereview
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /img/favicon\.ico
  static_files: /img/favicon.ico
  upload: /img/favicon\.ico

- url: /img
  static_dir: img

- url: /css/style\.css
  static_files: css/style.css
  upload: css/style\.css

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
